version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: dbuser
      POSTGRES_DB: keywordsdb
